name: Self Test - docker build action

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-build-scan-workflow:
    uses: ./.github/workflows/build-scan.yml
    with:
      working_directory: "tests/valid-app"
      dockerfile: "Dockerfile"
      image_name: "hello-world"
      image_tag: "latest"
      tag_latest: false
  
  test-invalid-build:
    name: Test - Invalid docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run docker build (invalid config)
        id: build
        uses: ./actions/build
        continue-on-error: true
        with:
          working_directory: "tests/invalid-build"
          image_name: "hello-world"
          image_tag: "invalid-build"

      - name: Assert failure
        run: |
          if [ "${{ steps.build.outputs.docker_build_exit_code }}" -eq 0 ]; then
            echo "Expected docker build to fail but it succeeded."
            exit 1
          fi
    
  test-invalid-scan:
    name: Test - Invalid docker scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run docker build (invalid config)
        id: build
        uses: ./actions/build
        with:
          working_directory: "tests/invalid-scan"
          image_name: "hello-world"
          image_tag: "invalid-scan"

      - name: Run docker scan (invalid config)
        id: scan
        uses: ./actions/scan
        continue-on-error: true
        with:
          working_directory: "tests/invalid-scan"
          image: "hello-world:invalid-scan"

      - name: Assert failure
        run: |
          if [ "${{ steps.scan.outputs.trivy_scan_exit_code }}" -eq 0 ]; then
            echo "Expected docker scan to fail but it succeeded."
            exit 1
          fi

